# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# Use npm to avoid yarn requirement; install prod deps only
COPY package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund

# Bundle app source
COPY . .

# Start the MCP HTTP server
CMD ["node", "index.js"]
